services:
  - type: web
    name: dmaz
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
